"$schema" = 'https://starship.rs/config-schema.json'

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[erlang]
symbol = "ⓔ "

[fortran]
symbol = "F "

[nodejs]
symbol = "[⬢](bold green) "

[pulumi]
symbol = "🧊 "

[typst]
symbol = "t "

[aws]
disabled = true

[git_metrics]
disabled = false

[git_status]
ahead = '↑'
behind = '↓'
diverged = '↑↓'
