#!/bin/bash

if [ -z "$1" ]; then
  {
    echo "BRANCH|LAST AUTHOR|LAST COMMIT|MESSAGE"
    git for-each-ref --sort=-committerdate refs/remotes/ \
      --format='%(refname:lstrip=3)|%(authorname)|%(committerdate:short)|%(contents:subject)'
  } \
    | column -t -s '|' \
    | fzf --header-lines=1 \
    | awk '{print $1}' \
    | xargs git switch
else
  git switch "$1"
fi