#!/bin/bash

if [ "$1" == "-" ]; then
    git checkout -
  elif [ -z $1 ]; then
  git for-each-ref --sort=-committerdate refs/heads/ --format='%(refname:short)' | fzf | xargs git checkout
else
  git for-each-ref --sort=-committerdate refs/heads/ --format='%(refname:short)' | fzf --query=$1 --select-1 --exit-0 | xargs git checkout
fi
