#!/bin/zsh

# remove old config files
rm -rf ~/.zshrc ~/.tmux.conf ~/.config/nvim ~/.config/starship.toml ~/.config/kitty/kitty.conf ~/.config/kitty/theme.conf

# link new config files
ln -s ~/dev/dotfiles/.zshrc ~/.zshrc
ln -s ~/dev/dotfiles/.tmux.conf ~/.tmux.conf
ln -s ~/dev/dotfiles/nvim ~/.config/nvim
ln -s ~/dev/dotfiles/starship.toml ~/.config/starship.toml
ln -s ~/dev/dotfiles/kitty.conf ~/.config/kitty/kitty.conf
ln -s ~/dev/dotfiles/theme.conf ~/.config/kitty/theme.conf
