#!/bin/zsh

languages=$(echo "typescript python golang rust c cpp" | tr " " "\n")
core_utils=$(echo "find xargs sed awk" | tr " " "\n")
selected=$(echo -e "$languages\n$core_utils" | fzf)

read -p "ENTER QUERY: " query

if echo "$languages" | grep -qs $selected; then
  curl cht.sh/$selected/$(echo "$query" | tr " " "+") | less
  # echo "I am lang"
else
  # echo "I am util"
  curl cht.sh/$selected~$query | less
fi

# Random