#!/bin/zsh

echo "👉  Syncing local configs FROM $CONFIG_DIR..."

rsync -av $CONFIG_DIR/dotfiles/.zshrc $HOME/.zshrc

echo "👈  Copying VS-Code config FROM repository..."
rsync -av $CONFIG_DIR/vscode/user/ $HOME/Library/Application\ Support/Code/User/

echo "👈  Copying VS-Code-Insisders config FROM repository..."
rsync -av $CONFIG_DIR/vscode-insiders/user/ $HOME/Library/Application\ Support/Code\ -\ Insiders/User/
