#!/bin/bash

scripts_dir="${SCRIPTS:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)}"
selected=$(find "$scripts_dir" -maxdepth 1 -type f -perm -111 -exec basename {} \; | sort | fzf)
if [ -n "$selected" ]; then
    exec "$scripts_dir/$selected"
fi
