#!/bin/zsh

SELECTED_DIR=$(find $DEV -type d -mindepth 1 -maxdepth 1 | fzf)

if [[ -z "$SELECTED_DIR" ]]; then
  exit 0
fi

SELECTED_NAME=$(basename $SELECTED_DIR | tr ":,. " "____")

switch_to() {
  if [[ -z $TMUX ]]; then
    tmux attach-session -t $SELECTED_NAME
  else
    tmux switch-client -t $SELECTED_NAME
  fi
}

if tmux has-session -t=$SELECTED_NAME 2> /dev/null; then
  switch_to
  exit 0
fi

tmux new-session -ds $SELECTED_NAME -c $SELECTED_DIR
switch_to
tmux send-keys -t $SELECTED_NAME "tmux_init" ^M

